platform:ios,'8.0'
pod 'Masonry'
pod 'SDCycleScrollView','~> 1.3'
pod 'AFNetworking'
pod 'SDWebImage', '~>3.7'
pod 'BaiduMapAPI', '~> 2.8.1'
pod 'SVProgressHUD'
pod 'IQKeyboardManager'
pod 'Mantle', '~> 2.0.5'
pod 'SSKeychain'
pod 'JPush', '~> 1.8.7'
pod 'NJKWebViewProgress'
pod 'MJRefresh'
pod 'EaseMobSDKFull', :git => 'https://github.com/easemob/sdk-ios-cocoapods-integration.git'
pod 'UMengAnalytics-NO-IDFA'
pod "Qiniu", "~> 7.0"




